### ISSUE TITLE
Ser colaborador do repositório da turma

### ISSUE THREAD

**Issue by hvenanc** [ramidedantas/GCMS-2022-2#4]
Gostaria de participar do repositório da turma.
@ramidedantas 
Atenciosamente, Henrique Venâncio @hvenac

**Comment by ramidedantas** [comment]
Convite realizado

**Comment by hvenanc** [comment]
Readme editado.

**Comment by ramidedantas** [comment]
@hvenanc crie uma issue com link conforme a Parte 3, Passo 3 e me marque.

**Comment by ramidedantas** [comment]
Ok, fechando.
